config/routes.rb
Rails.application.routes.draw do

  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')
  get 'signout', to: 'sessions#destroy', as: 'signout'
  resources :sessions, only: [:create, :destroy]

  resource :home, only: [:show]
  root to: "questions#index"
  resources :questions, except: [:destroy] do
    resources :answers, except: [:index, :show]
  end
end

app/models/answer.rb
class Answer < ApplicationModel
  attribute :body, Types::Strict::String
  attribute :question_id, Types::Strict::Int
  attribute :user_id, Types::Strict::Int
  attribute :user, Types::Constructor(User)
  attribute :question, Types::Constructor(Question)
  attribute :created_at, Types::Time
  attribute :updated_at, Types::Time
end

app/models/application_model.rb
require 'types'

class ApplicationModel < ROM::Struct
  def self.inherited(klass)
    super

    klass.extend ActiveModel::Naming
    klass.include ActiveModel::Conversion

    klass.constructor_type :schema

    klass.attribute :id, Types::Strict::Int.optional.meta(primary_key: true)
  end

  def persisted?
    id.present?
  end
end

app/models/question.rb
class Question < ApplicationModel
  attribute :title, Types::Strict::String
  attribute :body, Types::Strict::String
  attribute :answers, Types::Strict::Array.of(Answer).default([])
  attribute :user, Types::Constructor(User)
  attribute :created_at, Types::Time
  attribute :updated_at, Types::Time
end

app/models/user.rb
class User < ApplicationModel
  attribute :name, Types::Strict::String
  attribute :email, Types::Strict::String
  attribute :password, Types::Strict::String
  attribute :questions, Types::Strict::Array.of(Question).default([])
  attribute :answers, Types::Strict::Array.of(Answer).default([])
  attribute :created_at, Types::Time
  attribute :updated_at, Types::Time
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :get_question

  before_action :authorize, except: [:show, :index]

  before_action :load_searches, only: [:new, :create]

  def index
    @answers = repo.for_question(@question.id)
  end

  def new
    @answer = Answer.new
  end

  def create
    transaction = CreateAnswer.new
    transaction.(answer_params.merge!({ question_id: @question.id, user_id: @current_user.id })) do |result|
      result.success do |answer|
        flash[:notice] = "Answer has been created."
        redirect_to question_path(@question)
      end

      result.failure :validate do |errors|
        @answer = Answer.new(answer_params)
        @errors = errors
        flash[:alert] = "Answer could not be created."
        render :new
      end
    end
  end

  private

  def get_question
    @question = question_repo.by_id(params[:question_id])
  end

  def answer_params
    params.require(:answer).permit(:body).to_h.symbolize_keys
  end

  def question_repo
    QuestionRepository.new(ROM.env)
  end

  def repo
    AnswerRepository.new(ROM.env)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user
  helper_method :load_searches

  def current_user
    @current_user ||= user_repo.by_id(session[:user_id]) if signed_in?
  end

  private

  def signed_in?
    session[:user_id].present?
  end  

  def self.expose(variable_name)
    define_method(variable_name) do
      @exposed_variables ||= {}
      @exposed_variables[variable_name] ||= yield
    end
    helper_method variable_name
  end
  
  def load_searches
    @searches = SearchResults::Loader.new(current_user).load
  end

  def user_repo
    UserRepository.new(ROM.env)
  end

  def authorize
    redirect_to '/', notice: "You need to sign in" unless current_user
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :authorize, except: [:show, :index]

  before_action :load_searches, only: [:show, :new, :create]

  def index
    @questions = repo.query(params[:q], current_user)
    load_searches
  end

  def show
    @question = repo.by_id_with_answers_and_users(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    transaction = CreateQuestion.new
    transaction.(question_params.merge!({ user_id: @current_user.id })) do |result|
      result.success do |question|
        flash[:notice] = "Question has been created."
        redirect_to questions_path
      end

      result.failure :validate do |errors|
        @question = Question.new(question_params)
        @errors = errors
        flash[:alert] = "Question could not be created."
        render :new
      end
    end
  end

  private

  def question_params
    params.require(:question).permit(:title, :body, :q).to_h.symbolize_keys
  end


  def repo
    QuestionRepository.new(ROM.env)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = repo.from_omniauth(request.env["omniauth.auth"])
    user.is_a?(ROM::Struct::User) ? session[:user_id] = user.id : session[:user_id] = user.value.id
    redirect_to root_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def repo
    UserRepository.new(ROM.env)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown(text)
    options = {
      filter_html:     true,
      hard_wrap:       true,
      link_attributes: { rel: 'nofollow', target: "_blank" },
      space_after_headers: true,
      fenced_code_blocks: true
    }

    extensions = {
      autolink:           true,
      superscript:        true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/answers/_answer.html.erb
<div class="media-object stack-for-small">
  <div class="media-object-section">
      <h5><%= answer.user.name %></h5>
      <p><%= markdown(answer.body) %></p>
  </div>
</div>
<hr/>

app/views/answers/new.html.erb
<h2>Add answer</h2>
<h5><b>For question:</b> <%= @question.title %></h5>
<%= simple_form_for [@question, @answer], html: { novalidate: 'novalidate' } do |f| %>
  <%= render "shared/error_messages", errors: @errors %>

  <%= f.input :body, label: false, input_html: { class: 'textarea' } %>
  <%= f.submit 'Save', class: 'button'%>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "QA" %></title>

    <%= stylesheet_link_tag    "https://cdnjs.cloudflare.com/ajax/libs/foundation/6.2.4/foundation.css", "data-turbolinks-track": "reload" %>
    <%= stylesheet_link_tag    "application", "data-turbolinks-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbolinks-track": "reload" %>
    <%= csrf_meta_tags %>
  </head>

  <body>  
    <%= render 'shared/header' %>
    <div class="callout large">
       <div class="row column text-center">
       <h1>QA Board</h1>
       <p class="lead">Questions/Answers</p>
      <a href="<%= new_question_path %>" class="button large">Add question</a>
     </div>
    </div>
    <div class="row" id="content">
      <div class="medium-9 columns">
        <%= display_flash_messages %>
        <%= yield %>
      </div>
      <%= render 'shared/searches', searches: @searches %>
    </div>
  </body>
</html>

app/views/questions/_question.html.erb
<div class="blog-post">
  <h3><%= link_to question.title, question %> <small><%= question.created_at.strftime('%d/%m/%Y')  %></small></h3>
  <p><%= markdown(question.body) %></p>
  <div class="callout">
     <ul class="menu simple">
        <li><a href="#">Author: <%= question.user.name %></a></li>
        <li><a href="#">Answers: <%= question.answers.count %></a></li>
     </ul>
  </div>
</div>

app/views/questions/index.html.erb
<%= render @questions %>

app/views/questions/new.html.erb
<h2>New Project</h2>

<%= simple_form_for @question, html: { novalidate: 'novalidate' } do |f| %>
  <%= render "shared/error_messages", errors: @errors %>

  <%= f.input :title %>
  <%= f.input :body, input_html: { class: 'textarea' } %>
  <%= f.submit 'Save', class: 'button'%>
<% end %>

app/views/questions/show.html.erb
<div class="blog-post">
  <h3><%= @question.title %> <small><%= @question.created_at.strftime('%d/%m/%Y') %></small></h3>
  <h5>Author: <%= @question.user.name %></h5>
  <%= link_to '< questions list', questions_path %>
  <hr/>
  <% if current_user %>
    <a href="<%= new_question_answer_path(@question) %>" class="button secondary">Add answer</a>
  <% end %>
  <p><%= markdown(@question.body) %></p>
</div>

<% if @question.answers.any? %>
  <div class="column row">
    <ul class="tabs" data-tabs="5uxhud-tabs" id="example-tabs">
        <li class="tabs-title is-active" role="presentation">
        <a href="#" aria-selected="true" role="tab">Answers</a></li>
    </ul>
    <div class="tabs-content" data-tabs-content="example-tabs">
        <div class="tabs-panel is-active" id="panel1">
          <%= render @question.answers %>
        </div>
    </div>
  </div>
<% end %>

app/views/shared/_error_messages.html.erb
<% if errors.present? %>

<div class="callout alert">
    <p><%= pluralize(errors.count, "error") %> prohibited this todo from being saved:</p>

    
      <% errors.map do |key, messages| %>
        <% messages.each do |error| %>
          <p> - <%= key.to_s.capitalize %> <%= error %></p>
        <% end %>
      <% end %>
    
  </div>

<% end %>

app/views/shared/_header.html.erb
<div class="top-bar">
  <div class="row">
     <div class="top-bar-left">
        <ul class="dropdown menu" data-dropdown-menu="" role="menubar" data-dropdownmenu="3wqtyk-dropdownmenu">
          <li class="menu-text icon_menu" role="menuitem" tabindex="0"><%= link_to 'QA', root_path %></li>
          <% if current_user %>
            <li><%= link_to "Sign out: #{current_user.name}", signout_path, id: "sign_out" %></li>
          <% else %>
            <li><%= link_to "Sign in with Google", "/auth/google_oauth2", id: "sign_in" %></li>
          <% end %>
        </ul>
     </div>
     <div class="top-bar-right">
        <%= render 'shared/search_form' %>
     </div>
  </div>
</div>

app/views/shared/_search_form.html.erb
<%= form_tag(questions_path, method: :get) do |f| %>
  <ul class="menu">
      <li><%= text_field_tag :q, params[:q] %></li>
      <li><button type='submit' class="button">Search</button></li>
  </ul>
<% end %>

app/views/shared/_searches.html.erb
<div class="medium-3 columns">
  <h4>Last searches</h4>
  <ul class='menu vertical'>
    <% searches.each do |result| %>
      <li><span class="secondary label full_width"><a href="<%= questions_path(q: result) %>"><%= result %></a></span></li>
    <% end %>
  </ul>
</div>